# Generated by Django 5.2.6 on 2025-10-13 18:21

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='ID Único')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=50, verbose_name='Especie')),
                ('edad', models.PositiveIntegerField(help_text='Edad aproximada en años', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Edad (años)')),
                ('raza', models.CharField(max_length=100, verbose_name='Raza')),
                ('lugar_rescate', models.CharField(max_length=200, verbose_name='Lugar de Rescate')),
                ('fecha_rescate', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Rescate')),
                ('descripcion_medica', models.TextField(blank=True, help_text='Estado de salud, vacunas, tratamientos, etc.', verbose_name='Descripción Médica')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='animals/', verbose_name='Fotografía')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_proceso', 'En Proceso de Adopción'), ('adoptado', 'Adoptado'), ('cuarentena', 'En Cuarentena')], default='disponible', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'ordering': ['-fecha_rescate'],
            },
        ),
    ]
