# Generated by Django 5.2.6 on 2025-10-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='descripcion_medica',
            field=models.TextField(blank=True, help_text='Estado de salud, vacunas, tratamientos, etc.', null=True, verbose_name='Descripción Médica'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fecha_rescate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Rescate'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='lugar_rescate',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar de Rescate'),
        ),
    ]
